version: '3.5'
services:

    app:
        container_name: '${APP_NAME}-app'
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - .:/var/www/html
        networks:
            - test-foundarium-network
        depends_on:
            - mysql

    mysql:
        container_name: '${APP_NAME}-mysql'
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/data/mysql/database:/var/lib/mysql'
            - './docker/data/mysql/logs:/var/log/mysql'
        networks:
            - test-foundarium-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    adminer:
        container_name: '${APP_NAME}-adminer'
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - test-foundarium-network

networks:
    test-foundarium-network:
        driver: bridge
